# Generated by Django 4.0.3 on 2022-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөні')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер')),
                ('hotel', models.CharField(max_length=100, verbose_name='Қонақ үй')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.IntegerField(verbose_name='Балалар саны')),
                ('adult', models.IntegerField(verbose_name='Балалар саны')),
                ('date1', models.DateField(verbose_name='Алу куны')),
                ('date2', models.DateField(verbose_name='Откізу күні')),
            ],
        ),
    ]
