# Generated by Django 4.0.3 on 2022-03-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='created_at',
        ),
    ]
